#!/usr/bin/env bash
#SSH configuration without password but use the private key 
Host * 
        IndetityFile ~/.ssh/school
        PasswordAuthentication no
        HostName 52.90.54.149
        PreferredAuthentications publickey
        User ubuntu
