#!/usr/bin/env bash
#Double the number of webserver

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
	add_header X-Served-By \$HOSTNAME;
}
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "$config" > /etc/nginx/sites-available/default
sudo service nginx restart
