#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt update -y
sudo apt install haproxy -y
config=\
"backend my_servers
        balance roundrobin
        server 4818-web-01 35.172.220.65:80
        server 4818-web-02 34.204.53.150:80
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
