#!/usr/bin/env bash
# Using what I used in Task 0 but shorter
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
